// User
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';

export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SUCCESS_SIGN_OUT = 'SUCCESS_SIGN_OUT';
export const ERROR_SIGN_OUT = 'ERROR_SIGN_OUT';


// CAR
export const GET_CARS_PAGE_COUNT_REQUEST = 'GET_CARS_PAGE_COUNT_REQUEST';
export const GET_CARS_PAGE_COUNT_SUCCESS = 'GET_CARS_PAGE_COUNT_SUCCESS';
export const ERROR_GET_CARS_PAGE_COUNT = 'ERROR_GET_CARS_PAGE_COUNT';

export const GET_CARS_PAGE_REQUEST = 'GET_CARS_PAGE_REQUEST';
export const GET_CARS_PAGE_SUCCESS = 'GET_CARS_PAGE_SUCCESS';
export const ERROR_GET_CARS_PAGE = 'ERROR_GET_CARS_PAGE';

export const GET_CAR_REQUEST = 'GET_CAR_REQUEST';
export const GET_CAR_SUCCESS = 'GET_CAR_SUCCESS';
export const ERROR_GET_CAR = 'ERROR_GET_CAR';

export const SAVE_CAR_REQUEST = 'SAVE_CAR_REQUEST';
export const ADD_CAR_SUCCESS = 'ADD_CAR_SUCCESS';
export const ERROR_ADD_CAR = 'ERROR_ADD_CAR';

export const UPDATE_CAR_REQUEST = 'UPDATE_CAR_REQUEST';
export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS';
export const ERROR_UPDATE_CAR = 'ERROR_UPDATE_CAR';

export const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const ERROR_DELETE_CAR = 'ERROR_DELETE_CAR';







